## NumPy (Numerical Python), 
Python listelerine kıyasla bellek yönetimi ve hız açısından çok daha optimize edilmiş, **C** tabanlı bir kütüphanedir. Veri biliminde matris ve vektör işlemleri için standart kabul edilir.

---

In [2]:
import numpy as np

In [6]:
# Klasik bir Python Listesi
myList = [10, 20, 30, 40]
print(type(myList))  

<class 'list'>


In [7]:
# Python listesini NumPy Array'ine (dizisine) dönüştürme
my_numpy_array = np.array(myList)
print(type(my_numpy_array)) 

<class 'numpy.ndarray'>


In [8]:
# Not: Aşağıdaki gibi bir listeyi doğrudan da array'e çevirebiliriz.
veri_listesi = [1, 2, 3, 4, 5]
numpy_dizisi = np.array(veri_listesi)

---
### Vektörel İşlemler (Element-wise Operations)
Python listelerinde + operatörü listeleri yan yana birleştirirken (concatenation), NumPy array'lerinde matematiksel işlemler karşılıklı elemanlar (element-wise) üzerinden yapılır.

---

In [9]:
# Python listelerinde davranış
my_list1 = [1, 2]
my_list2 = [2, 3]

In [10]:
# NumPy Array'lerinde davranış
my_npmy_array1 = np.array(my_list1)
my_npmy_array2 = np.array(my_list2)

In [12]:
# Matematiksel operatörler doğrudan elemanlara uygulanır
print(my_npmy_array1 + my_npmy_array2)
print(my_npmy_array1 * my_npmy_array2) 
print(my_npmy_array1 - my_npmy_array2) 
print(my_npmy_array1 / my_npmy_array2) 

[3 5]
[2 6]
[-1 -1]
[0.5        0.66666667]


---
### Array Üretme Yöntemleri
NumPy, belirli örüntülerde veya rastgele değerlerle array oluşturmak için çok güçlü dahili fonksiyonlara sahiptir.

---

In [14]:
# Python'un yerleşik fonksiyonu ile liste üretme
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
# NumPy ile belirli adımlarla array üretme (başlangıç, bitiş, adım)
np.arange(0, 10, 2)
np_array = np.arange(0, 10)

In [18]:
# Rastgele Veri Üretimi
print(np.random.randn(4))     # Standart normal dağılımdan 4 değer çeker
print("-"*30)
print(np.random.randn(4, 4))  # Normal dağılımdan rastgele değerlerle 4x4'lük matris oluşturur

[0.46144313 0.48034461 0.32936577 1.20480166]
------------------------------
[[-0.53366603  0.87560868  1.7584374  -1.31561973]
 [ 0.10488492 -0.68497784  1.31467158  0.21239701]
 [ 1.02411826  0.98075189 -0.5539585   1.30511713]
 [ 0.64645627  0.09137425 -0.34506845 -1.00706955]]


In [19]:
# Belirli bir aralıkta tam sayı (Integer) üretme (low, high, size)
np.random.randint(1, 300, 5) # 1 ile 300 arasında rastgele 5 adet sayı üretir

array([281, 163, 217, 255, 172], dtype=int32)

---
### İndeksleme ve Parçalama (Slicing)
Tek boyutlu NumPy dizilerinde indeksleme, klasik Python listeleriyle birebir aynı mantıkta çalışır.

---

In [21]:
np_array = np.arange(0, 10)

np_array[-1]     # Son elemanı getirir (9)
np_array[0]      # İlk elemanı getirir (0)

np.int64(0)

In [22]:
# Slicing: [başlangıç : bitiş : adım]
np_array[1:10:2] # 1. indeksten başla, 10'a kadar 2'şer atlayarak git
np_array[::-1]   # Array'i tersine çevirir (Reverse işlemi)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

---
### Matrisler ve Skaler İşlemler
Makine öğreniminde veriler genellikle 2 boyutlu (satır ve sütunlar - tabular veri) veya daha çok boyutlu tensörler olarak temsil edilir.

---

In [23]:
# İç içe listelerden matris oluşturma
my_matrix = [[5, 10], [15, 20]]
my_matrix[1][0] # 2. listenin ilk elemanına (15) erişim

15

In [24]:
# Matrisi NumPy dizisine çevirme
numpy_matrix = np.array([[5, 10], [15, 20]])

# Toplam ve Özel Matrisler
numpy_matrix.sum()        # Matristeki tüm değerleri toplar (50)
np.ones((3, 2))           # Sadece 1'lerden oluşan 3 satır, 2 sütunlu matris
np.zeros((3, 5))          # Sadece 0'lardan oluşan 3 satır, 5 sütunlu matris
np.random.random((4, 4))  # 0.0 ile 1.0 arasında rastgele değerlerle 4x4 matris

array([[0.56148977, 0.63231029, 0.17882248, 0.90606151],
       [0.0183396 , 0.22960618, 0.9546833 , 0.48694487],
       [0.62356425, 0.75797806, 0.83065866, 0.68931622],
       [0.87549974, 0.95830049, 0.07467285, 0.30523146]])

In [25]:
# Skaler İşlemler (Tekil bir sayıyı matrise uygulama)
first_array = np.array([[10, 20], [30, 40]])
first_array * 3 # Tüm elemanları 3 ile çarpar
first_array / 2 # Tüm elemanları 2'ye böler
first_array + 5 # Tüm elemanlara 5 ekler

array([[15, 25],
       [35, 45]])

---
### Broadcasting ve Matris Çarpımı (Dot Product)
Broadcasting: İki farklı boyuttaki array işleme girdiğinde, NumPy küçük olan boyutu mantıksal olarak "genişleterek" işleme uygun hale getirir.

---

In [28]:
first_array = np.array([[10, 20], [30, 40]]) # shape: (2, 2)
third_array = np.array([[10], [20]])         # shape: (2, 1)

# third_array, (2,2) boyutuna sanal olarak yayılarak (broadcast) toplanır.
third_array + first_array

array([[20, 30],
       [50, 60]])

---
### Dot Product (Matris Çarpımı):
Makine öğrenimindeki yapay sinir ağlarının temel taşıdır. Karşılıklı elemanların çarpılıp toplanmasına dayanır.Kural: 1. matrisin sütun (column) sayısı ile 2. matrisin satır (row) sayısı **EŞİT** olmalıdır. Sonuç matrisinin boyutu: (1. matrisin satır sayısı) x (2. matrisin sütun sayısı) olur.Matematiksel gösterimi: $(m \times n) \cdot (n \times p) = (m \times p)$

In [31]:
first_matrix = np.array([[10, 20, 30]]) # 1 satır, 3 sütun -> shape (1, 3)
second_matrix = np.array([[2, 3], 
                          [2, 3], 
                          [2, 3]])      # 3 satır, 2 sütun -> shape (3, 2)

# (1, 3) . (3, 2) = (1, 2) boyutunda sonuç beklenir.
result_matrix = first_matrix.dot(second_matrix)
print(result_matrix.shape)

(1, 2)


---
### Koşullu Seçim (Boolean Masking)
Veri setindeki istenmeyen veya belirli şartlara uyan verileri filtrelemek (örneğin anomalileri çıkarmak) için sıklıkla kullanılır.

---

In [32]:
new_array = np.random.randint(1, 100, 20) # 1-100 arası 20 sayı

# Her bir eleman için koşulu test eder ve True/False array'i döndürür
print(new_array > 25) 

# Köşeli parantez içine koşulu yazdığımızda, sadece True olan değerleri filtreler
filtrelenmis_veri = new_array[new_array > 25]

[ True  True  True  True  True  True False  True  True False  True  True
  True  True  True  True  True  True  True  True]


---
### Şekillendirme (Reshape) ve Transpoz (Transpose)
Array boyutlarını veriye zarar vermeden (toplam eleman sayısını sabit tutarak) yeniden düzenlemek, modellerin girdi (input) şekillerini ayarlarken kritik bir adımdır.

--- 

In [33]:
matrix_array = np.array([[10, 20], [20, 30], [30, 40]]) # shape: (3, 2)

# Transpoze: Satırları sütun, sütunları satır yapar.
matrix_array.transpose() 
matrix_array.T # Yukarıdaki işlemle tamamen aynıdır (Kısa yazım)

# Reshape: Array'in şeklini yeniden boyutlandırma
random_array = np.random.random((6, 1)) # 6 elemanlı (6, 1) boyutlu vektör

# Toplam eleman sayısı (6x1=6) sabit kaldığı sürece farklı şekillere sokulabilir:
random_array.reshape(2, 3) # 2 satır, 3 sütunlu matrise çevirir (2x3=6)
random_array.reshape(3, 2) # 3 satır, 2 sütunlu matrise çevirir (3x2=6)

array([[0.37041794, 0.60858839],
       [0.72805899, 0.46754207],
       [0.12000414, 0.76711123]])